/**
 * Recovers a single payload bit from 64 complex chips using DSSS Correlation.
 * @param complexChips 64 [Real, Imag] pairs extracted from safeBins
 * @param pnSequence 64-chip sequence generated by the LFSR
 * @returns The recovered bit
 */

export function despreadBit(
  complexChips: Float32Array,
  pnSequence: Float32Array,
): number {
  let totalPhaseShift = 0;

  for (let i = 0; i < pnSequence.length; i++) {
    const real = complexChips[i * 2]!;
    const imag = complexChips[i * 2 + 1]!;
    const pnChip = pnSequence[i]!;

    const currentPhase = Math.atan2(imag, real);

    const magnitude = Math.sqrt(real * real + imag * imag);

    totalPhaseShift += currentPhase * pnChip * magnitude;
  }
  return totalPhaseShift > 0 ? 1 : 0;
}
